### PR TITLE
Add operating systems

### PR DESCRIPTION
**Pull request by ShiroTohu**
### Changes Made
I saw in the To-Do list that you wanted to possibly add operating systems. So I went through each game and listed what platforms they support and used [Shields.io](https://shields.io/badges) to create the supported operating system icons as I thought it was a little fitting and cool looking. I used the steam page for each game to determine their supported platforms.

**Note: For Star Ruler 2, it doesn't state the supported operating systems on Steam (at a glance). Therefore I went to their GitHub page instead to see what operating systems allowed you to build the game.**

I also changed some other things as well:
 - resources was spelt ressources.
 - ? and ! have whitespace surrounding them. (There might be a reason why it is formatted this way that I am unaware of).
 - I added double line breaks between each game to make each game more discernible when editing.
 - Removed bullet point for each game. See section below for more details.
 - Added HTML comments for the supported operating systems & HyperLinks in an effort to separate it from everything else.
 - Crossed out the "add supported platforms" text in the To-Do List.
 
 ### Removed Bullet Point For Each Game
 If you also would like to keep those bullet points I could change it so that it looks something like this
 ```markdown
 - ## Amnesia: A Machine for Pigs
    <!-- Supported Operating Systems -->
    ![Static Badge](https://img.shields.io/badge/Windows-2f81f7?style=for-the-badge&logo=windows10&logoColor=white)
    ![Static Badge](https://img.shields.io/badge/MacOS-f0f0f0?style=for-the-badge&logo=apple&logoColor=black)
    ![Static Badge](https://img.shields.io/badge/SteamOS%2FLinux-%23272932?style=for-the-badge&logo=steam)

    <!-- HyperLinks -->
    [Game on Steam](https://store.steampowered.com/app/239200/Amnesia_A_Machine_for_Pigs/) | [Source Code](https://github.com/FrictionalGames/AmnesiaAMachineForPigs) | [GNU General Public License v3.0](https://github.com/FrictionalGames/AmnesiaAMachineForPigs/blob/master/LICENSE) | [Website](http://www.aamfp.com/info)

    From the creators of Amnesia: The Dark Descent and Dear Esther comes a new first-person horror game that will drag you to the depths of greed, power and madness. It will bury its snout into your ribs and it will eat your heart.
 ```
 That way the rendered result can look like this:
 - ## Amnesia: A Machine for Pigs
    
    Static Badge
    Static Badge
    Static Badge

    
    [Game on Steam](https://store.steampowered.com/app/239200/Amnesia_A_Machine_for_Pigs/) | [Source Code](https://github.com/FrictionalGames/AmnesiaAMachineForPigs) | [GNU General Public License v3.0](https://github.com/FrictionalGames/AmnesiaAMachineForPigs/blob/master/LICENSE) | [Website](http://www.aamfp.com/info)

    From the creators of Amnesia: The Dark Descent and Dear Esther comes a new first-person horror game that will drag you to the depths of greed, power and madness. It will bury its snout into your ribs and it will eat your heart.

That way the text is aligned on the left hand side and it has a more grouped feeling. 

### Additional Changes
If you are not happy with the proposed changes, feel free to change anything or let me know!

### CODE REVIEW

**Comment by Poussinou** [comment]
WHAAAAAA,

I missed the notification for this Pull Request, but that looks amazing! I agree with all the changes you did. Removing the bullet points make it look better yep.

> ? and ! have whitespace surrounding them. (There might be a reason why it is formatted this way that I am unaware of).
That's the convention in French which is my native language. Good that you corrected this!

Again, thanks for this contribution, it looks amazing and add some interesting information for the users!

**Comment by Poussinou** [comment]
@ShiroTohu 
May I invite you to join me as a collaborator on this project? You'll be able to push commits directly, respond to the Issues or add games if you want. No 
I really appreciated your qualitative contribution, and I do not necessarily have a lot of time to maintain this. No obligation, no stress, just some contribution to help people switch to FLOSS :)

**Comment by ShiroTohu** [comment]
Sure, I wouldn't mind helping out from time to time.

**Comment by Poussinou** [comment]
Ok I sent you the invitation

**Pull request merged**
