### PR TITLE
Add tModLoader

### PR DESCRIPTION
**Pull request by rammba**
Hello, I'm happy to see this database of open-source games. Great work!
I'm adding [tModLoader](https://store.steampowered.com/app/1281930/tModLoader/) which is not actual game but more DLC or `Community-Made Mod`.
@Poussinou Is this kind of Steam games also intended to be here?

### CODE REVIEW

**Comment by Poussinou** [comment]
Hello @rammba 
First time I encounter this case, honestly. After thinking about it, I suppose we can keep it in the list (goal being to increase the use of FLOSS stuff on Steam, which is the case here).

Two requests : 
* Change "Game on Steam" to "Mod on Steam"
* In the description, add a small sentence specifying that you need to own a Terraria licence to use this Mod, and that Terraria is proprietary software.

Other than that, thanks for the contribution. Really happy to hear people saying that the list is interesting/useful :)

**Comment by rammba** [comment]
Hi @Poussinou 
Thanks for the suggestions.
I also found that FLOSS software (#36) is available on the Steam. If you agree, we can investigate and add those here.

**Comment by rammba** [comment]
Hey @Poussinou can we merge this?

**Comment by Poussinou** [comment]
Hey @rammba sorry for lagging behind on this... I'm just gonna merge this as it looks good now. I'll also change the description of the repo to something that includes FLOSS "games, mods, and software" to reflect the presence of this mod.

As you have made quite a few good contributions and I don't have much time for this repo, I also sent you an invit to become a contributor to this repo, you'll be able to push commits directly, merge PR, etc... Feel free to join!

**Comment by rammba** [comment]
Thanks for the invite. I will investigate a little bit and add few free softwares that I find.

**Pull request merged**
